### ISSUE TITLE
Add a general message component at the top of the main page

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app#1]
Any component should be able to generate messages to the user. This message can be of different types from information to error. Please consider [W3 School's Alert](https://www.w3schools.com/bootstrap/bootstrap_alerts.asp). Include in the main component a message component that can be activated with a message string and a class of the message (error to information).

Also have a look at the validation errors generated in [lines 12 to 14 of formElements.ejs](https://github.com/ScienceDb/single-page-app-codegen/blob/master/views/pages/formElements.ejs)

### Expected work time: 6 hours

**Comment by vsuaste** [comment]
Done. [#3647d8](https://github.com/ScienceDb/single-page-app/commit/3647d84abbaf151480e91d1719c47db04df0880e)
Still we need to use the component for errors in the spa
