### ISSUE TITLE
Login URL is fixed. Switch to usage of base URL variable.

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app#4]
In line 38 of module [`store.js`](https://github.com/ScienceDb/single-page-app/blob/master/src/store.js) the URL used to login a user is fixed to `localhost`. 

Please fix to usage of `sciencedb-globals.js` `$baseUrl`.

### Expected work time: 1h

**Comment by vsuaste** [comment]
A new environment variable (`MY_LOGIN_URL`)  was defined. Although server url and login url should share the same base url both of them have different endpoint `graphql` and `login` correspondingly. Remember we have an environment variable for the server url (`MY_SERVER_URL`).

Another solution could have been define the environmental variables only for the endpoints.

**Comment by vsuaste** [comment]
Done. [#40bd11](https://github.com/ScienceDb/single-page-app/commit/40bd1160ce6603c100058d59995b51a0b9b96a7e)
