### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app#5]
Currently there is a little paragraph about "Expected environment variables":
```
AUTH0_DOMAIN
AUTH0_CLIENT_ID
YOUR_CALLBACK_URL
MY_SERVER_URL 
```

To my knowledge the above `AUTH0_*` are no longer part of the project? If they still are, they certainly are not mandatory, are they?
Also the environment variable `PORT` is not mentioned.

Please ensure the README _and_ our manual are up to date and contain a comprehensive and complete documentation.

### Expected work time: 30 minutes

**Comment by vsuaste** [comment]
Done. Commits: [#050ded](https://github.com/ScienceDb/ScienceDb.github.io/commit/050ded37b578d3d2f79fe81b0162d9b876a5ba84) [#3d6014](https://github.com/ScienceDb/ScienceDb.github.io/commit/3d6014f689a653a294e7bb01e617c209ff5ba686) [#141521](https://github.com/ScienceDb/ScienceDb.github.io/commit/141521539269635ee56add62c462da35a2c2d0df) [#f74b68](https://github.com/ScienceDb/single-page-app/commit/f74b68462768042e416010a52b4237ed9b695593)

### Actual work time: 25 minutes

### NOTE : I just opened another [issue](https://github.com/ScienceDb/single-page-app/issues/6) to allow PORT in the SPA to be modified via environment variable.
